version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
    nodejs: "22"
  commands:
    - npm install -g mystmd
    - myst build docs --html
    - mkdir -p $READTHEDOCS_OUTPUT/html/
    - cp -r docs/_build/html/. "$READTHEDOCS_OUTPUT/html"

python:
  install:
    - method: pip
      path: .[docs]



        

