version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
    nodejs: "22"
  commands:
  - npm install -g mystmd
  - bash -lc "cd docs && myst build --all && ls -la _build"
  - bash -lc "mkdir -p $READTHEDOCS_OUTPUT/html"
  - bash -lc "cp -r docs/_build/html/. $READTHEDOCS_OUTPUT/html"
  - bash -lc "mkdir -p $READTHEDOCS_OUTPUT/html/exports"
  - bash -lc "cp -r docs/_build/exports/. $READTHEDOCS_OUTPUT/html/exports"
  
python:
  install:
    - method: pip
      path: .[docs]



        

