version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
    nodejs: "22"
  commands:
    - npm install -g mystmd
    - bash -lc "cd docs && myst build --all"
    - bash -lc "mkdir -p $READTHEDOCS_OUTPUT/html && cp -r docs/_build/html/. $READTHEDOCS_OUTPUT/html"
    - bash -lc "mkdir -p $READTHEDOCS_OUTPUT/html/exports && cp -r docs/_build/exports/. $READTHEDOCS_OUTPUT/html/exports"

python:
  install:
    - method: pip
      path: .[docs]



        

